### ISSUE TITLE
Model sizes and runtimes for PWC-Net, PWC-Net-ROB and PWC-Net+

### ISSUE THREAD

**Issue by twhui** [NVlabs/PWC-Net#61]
Are there any differences between PWC-Net, PWC-Net-ROB and PWC-Net+ in terms of runtime and model size in the paper "Models Matter, So Does Training: An Empirical Study of CNNs for Optical Flow Estimation"?

Could you please clarify whether the provided model (Caffe/model/pwc_net.caffemodel) is PWC-Net-ft in CVPR18 or PWC-Net-ROB in CVPRW18?

**Comment by deqings** [comment]
Thanks for your interest in our work and sorry for the late reply. PWC-Net (CVPR18) and PWC-Net+ have the same architecture but different weights. PWC-Net-ROB is from CVPRW18 and has similar running time as PWC-Net. PWC-Net-ROB has slightly larger model size due to an additional layer in the encoder.

The provided model is PWC-Net-ROB and PWC-Net+ will be provided very soon.

**Comment by MaybeOjbk** [comment]
Is the running time you proposed implemented by Caffee?  not in Pytorch ?
